Update index.js
Switches protocol from default (TLSv2) to TLSv1. This fixed an issue with my E55-D0 running software version 2.0.17/cast version 1.22.78594 where Homebridge was throwing the following error:
RequestError: Error: write EPROTO 140736109753216:error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol:../deps/openssl/openssl/ssl/statem/statem_lib.c:1994

 This would probably be better implemented as a fallback if requests to the TV are throwing the "unsupported protocol" error in order to avoid potentially breaking compatibility with newer TVs. But I am not very familiar with js, so this was my bootstrap solution.